-- Lisää DROP TABLE lauseet tähän tiedostoon

DROP TABLE IF EXISTS Kisa CASCADE;
DROP TABLE IF EXISTS Kilpailija CASCADE;
DROP TABLE IF EXISTS Valipiste CASCADE;
DROP TABLE IF EXISTS Aika CASCADE;
DROP TABLE IF EXISTS Kisanumero CASCADE;
DROP TABLE IF EXISTS Kayttaja CASCADE;